title: "The Code Den"
description: "I *do not* know what I am doing™"
paginate: 5
paginate_path: "blog/:num/"
livereload: true

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
